# Generated by Django 3.0.5 on 2021-05-16 10:38

from django.db import migrations, models
import djongo.models.fields
import shiristory.story_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('group_members', djongo.models.fields.JSONField()),
                ('group_admins', djongo.models.fields.JSONField()),
                ('date_created', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Finished')])),
                ('vote_duration', models.DurationField()),
                ('vote_threshold', models.IntegerField()),
                ('stories', djongo.models.fields.ArrayField(model_container=shiristory.story_service.models.StoryObject, model_form_class=shiristory.story_service.models.StoryObjectForm)),
                ('vote_pool', djongo.models.fields.EmbeddedField(model_container=shiristory.story_service.models.VotePool)),
            ],
        ),
        migrations.CreateModel(
            name='StoryObject',
            fields=[
                ('story_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('story_type', models.IntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'Audio'), (3, 'Video')])),
                ('story_content', models.CharField(max_length=255)),
                ('next_story_type', models.IntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'Audio'), (3, 'Video')])),
                ('datetime', models.DateTimeField()),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VotePool',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('vote_end_time', models.DateTimeField()),
                ('candidates', djongo.models.fields.ArrayField(model_container=shiristory.story_service.models.StoryObject, model_form_class=shiristory.story_service.models.StoryObjectForm)),
            ],
        ),
    ]
