version: '3'

services:
  shiristory:
    container_name: shiristory
    restart: always
    build: .
    depends_on:
      - mongodb
    expose:
      - "8000"
      - "7999"
    volumes:
      - .:/course/code/
    networks:
      - web_network
      - db_network
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "7999:7999"
      - "8000:8000"
    depends_on:
      - shiristory
    volumes:
      - ./nginx/shiristory-dev.conf:/etc/nginx/conf.d/shiristory.conf
      - ./media:/course/code/media
    networks:
      - web_network

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - db_network

  mongodb:
    container_name: mongodb
    restart: always
    build: ./mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb/:/docker-entrypoint-initdb.d/
      - mongo-volume:/data/db
    networks:
      - db_network

volumes:
  mongo-volume:

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge