version: '3'

services:
  shiristory:
    container_name: shiristory
    restart: always
    build: .
    depends_on:
      - mongodb
    expose:
      - "8000"
    volumes:
      - code-volume:/course/code/
    networks:
      - web_network
      - db_network
    command: gunicorn -w 4 -k gthread -b 0.0.0.0:8000 shiristory.wsgi

  shiristory_ws:
    container_name: shiristory_ws
    restart: always
    build: .
    depends_on:
      - shiristory
    command: daphne -b 0.0.0.0 -p 7999 shiristory.asgi:application
    expose:
      - "7999"
    volumes:
      - code-volume:/course/code/
    networks:
      - web_network
      - db_network


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "7999:7999"
      - "8000:8000"
    depends_on:
      - shiristory
    volumes:
      - media-volume:/course/code/media
    networks:
      - web_network

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    expose:
      - "6379"
    networks:
      - db_network

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-volume:/data/db
    networks:
      - db_network

volumes:
  mongo-volume:
  media-volume:
  code-volume:

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge