# Generated by Django 3.0.5 on 2021-05-20 07:59

from django.db import migrations, models
import djongo.models.fields
import shiristory.timeline_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=500)),
                ('inv_link', models.URLField()),
                ('media', models.URLField()),
                ('media_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', djongo.models.fields.EmbeddedField(model_container=shiristory.timeline_service.models.Comment)),
            ],
        ),
    ]
