# Generated by Django 3.0.5 on 2021-05-24 17:06

from django.db import migrations
import djongo.models.fields
import shiristory.timeline_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=djongo.models.fields.ArrayField(model_container=shiristory.timeline_service.models.Comment),
        ),
    ]
